[package]
name = "solana-mvp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
jito-protos = { path = "../shredstream-proxy/jito_protos" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
solana-client = "2"
solana-sdk = "2"
